name: ci-build

on:
  schedule:
    - cron: "5 3 * * 0"
  push:
    branches:
      - "main"

jobs:
  base-ubuntu:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push frankenphp8.3
        uses: docker/build-push-action@v4
        with:
          context: 8.3/.
          platforms: linux/amd64,linux/arm64
          push: true
          tags: falki141/frankenphp-hardened:8.3
      -
        name: Build and push frankenphp8.4
        uses: docker/build-push-action@v4
        with:
          context: 8.4/.
          platforms: linux/amd64,linux/arm64
          push: true
          tags: falki141/frankenphp-hardened:8.4

      - name: Build and push frankenphp8.5
        uses: docker/build-push-action@v4
        with:
          context: 8.5/.
          platforms: linux/amd64,linux/arm64
          push: true
          tags: falki141/frankenphp-hardened:8.5